# Generated by Django 5.0.6 on 2026-05-08 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_alter_transaction_voter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bundle_enabled',
            field=models.BooleanField(default=False, help_text='Toggle bundle pricing on or off.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='bundle_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price for one bundle.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='bundle_size',
            field=models.PositiveIntegerField(default=1, help_text='Number of votes per bundle.'),
        ),
    ]
