# Generated by Django 5.0.6 on 2026-05-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_event_bundle_enabled_alter_event_bundle_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_votes_per_transaction',
            field=models.PositiveIntegerField(default=1000, help_text='Maximum votes allowed in a single transaction. Set to 0 for unlimited.'),
        ),
    ]
