[program:opencastgh_gunicorn]
command=/home/ubuntu/venv/bin/gunicorn opencastgh.wsgi:application --workers 3 --bind 127.0.0.1:8000
directory=/home/ubuntu/opencastgh
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/opencastgh/gunicorn.log

[program:opencastgh_celery]
command=/home/ubuntu/venv/bin/celery -A opencastgh worker --loglevel=info
directory=/home/ubuntu/opencastgh
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/opencastgh/celery.log

[program:opencastgh_celery_beat]
command=/home/ubuntu/venv/bin/celery -A opencastgh beat --loglevel=info
directory=/home/ubuntu/opencastgh
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/opencastgh/celery_beat.log
