[program:opencastmain_gunicorn]
command=/home/ubuntu/venv/bin/gunicorn opencastmain.wsgi:application --workers 3 --bind 127.0.0.1:8000
directory=/home/ubuntu/opencastgh
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/opencastmain/gunicorn.log

[program:opencastmain_celery]
command=/home/ubuntu/venv/bin/celery -A opencastmain worker --loglevel=info
directory=/home/ubuntu/opencastgh
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/opencastmain/celery.log

[program:opencastmain_celery_beat]
command=/home/ubuntu/venv/bin/celery -A opencastmain beat --loglevel=info
directory=/home/ubuntu/opencastgh
user=ubuntu
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/opencastmain/celery_beat.log
